//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomaMove.Doma
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.matstroeng.se/doma", ConfigurationName="DomaMove.Doma.DOMAServicePortType")]
    public interface DOMAServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rystad.no/kart/webservice.php/PublishMap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Category))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        System.Threading.Tasks.Task<DomaMove.Doma.PublishMapResponse> PublishMapAsync(DomaMove.Doma.PublishMapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rystad.no/kart/webservice.php/PublishPreUploadedMap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Category))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        System.Threading.Tasks.Task<DomaMove.Doma.PublishPreUploadedMapResponse> PublishPreUploadedMapAsync(DomaMove.Doma.PublishPreUploadedMapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rystad.no/kart/webservice.php/UploadPartialFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Category))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        System.Threading.Tasks.Task<DomaMove.Doma.UploadPartialFileResponse> UploadPartialFileAsync(DomaMove.Doma.UploadPartialFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rystad.no/kart/webservice.php/GetAllMaps", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Category))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        System.Threading.Tasks.Task<DomaMove.Doma.GetAllMapsResponse> GetAllMapsAsync(DomaMove.Doma.GetAllMapsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rystad.no/kart/webservice.php/GetAllCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Category))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        System.Threading.Tasks.Task<DomaMove.Doma.GetAllCategoriesResponse> GetAllCategoriesAsync(DomaMove.Doma.GetAllCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rystad.no/kart/webservice.php/Connect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Category))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        System.Threading.Tasks.Task<DomaMove.Doma.ConnectResponse> ConnectAsync(DomaMove.Doma.ConnectRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class PublishMapRequest
    {
        
        private string usernameField;
        
        private string passwordField;
        
        private MapInfo mapInfoField;
        
        /// <remarks/>
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public MapInfo MapInfo
        {
            get
            {
                return this.mapInfoField;
            }
            set
            {
                this.mapInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class MapInfo
    {
        
        private int idField;
        
        private int userIDField;
        
        private int categoryIDField;
        
        private System.DateTime dateField;
        
        private string nameField;
        
        private string organiserField;
        
        private string countryField;
        
        private string disciplineField;
        
        private string relayLegField;
        
        private string mapNameField;
        
        private string resultListUrlField;
        
        private string commentField;
        
        private byte[] mapImageDataField;
        
        private string mapImageFileExtensionField;
        
        private byte[] blankMapImageDataField;
        
        /// <remarks/>
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public int CategoryID
        {
            get
            {
                return this.categoryIDField;
            }
            set
            {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Organiser
        {
            get
            {
                return this.organiserField;
            }
            set
            {
                this.organiserField = value;
            }
        }
        
        /// <remarks/>
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Discipline
        {
            get
            {
                return this.disciplineField;
            }
            set
            {
                this.disciplineField = value;
            }
        }
        
        /// <remarks/>
        public string RelayLeg
        {
            get
            {
                return this.relayLegField;
            }
            set
            {
                this.relayLegField = value;
            }
        }
        
        /// <remarks/>
        public string MapName
        {
            get
            {
                return this.mapNameField;
            }
            set
            {
                this.mapNameField = value;
            }
        }
        
        /// <remarks/>
        public string ResultListUrl
        {
            get
            {
                return this.resultListUrlField;
            }
            set
            {
                this.resultListUrlField = value;
            }
        }
        
        /// <remarks/>
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] MapImageData
        {
            get
            {
                return this.mapImageDataField;
            }
            set
            {
                this.mapImageDataField = value;
            }
        }
        
        /// <remarks/>
        public string MapImageFileExtension
        {
            get
            {
                return this.mapImageFileExtensionField;
            }
            set
            {
                this.mapImageFileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] BlankMapImageData
        {
            get
            {
                return this.blankMapImageDataField;
            }
            set
            {
                this.blankMapImageDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class ConnectResponse
    {
        
        private bool successField;
        
        private string errorMessageField;
        
        private string versionField;
        
        /// <remarks/>
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class ConnectRequest
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class Category
    {
        
        private int idField;
        
        private int userIDField;
        
        private string nameField;
        
        /// <remarks/>
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class GetAllCategoriesResponse
    {
        
        private bool successField;
        
        private string errorMessageField;
        
        private Category[] categoriesField;
        
        /// <remarks/>
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public Category[] Categories
        {
            get
            {
                return this.categoriesField;
            }
            set
            {
                this.categoriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class GetAllCategoriesRequest
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class GetAllMapsResponse
    {
        
        private bool successField;
        
        private string errorMessageField;
        
        private MapInfo[] mapsField;
        
        /// <remarks/>
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public MapInfo[] Maps
        {
            get
            {
                return this.mapsField;
            }
            set
            {
                this.mapsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class GetAllMapsRequest
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class UploadPartialFileResponse
    {
        
        private bool successField;
        
        private string errorMessageField;
        
        private string fileNameField;
        
        /// <remarks/>
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class UploadPartialFileRequest
    {
        
        private string usernameField;
        
        private string passwordField;
        
        private string fileNameField;
        
        private byte[] dataField;
        
        /// <remarks/>
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class PublishPreUploadedMapResponse
    {
        
        private bool successField;
        
        private string errorMessageField;
        
        private string uRLField;
        
        /// <remarks/>
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string URL
        {
            get
            {
                return this.uRLField;
            }
            set
            {
                this.uRLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class PublishPreUploadedMapRequest
    {
        
        private string usernameField;
        
        private string passwordField;
        
        private MapInfo mapInfoField;
        
        private string preUploadedMapImageFileNameField;
        
        private string preUploadedBlankMapImageFileNameField;
        
        private string preUploadedThumbnailImageFileNameField;
        
        /// <remarks/>
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public MapInfo MapInfo
        {
            get
            {
                return this.mapInfoField;
            }
            set
            {
                this.mapInfoField = value;
            }
        }
        
        /// <remarks/>
        public string PreUploadedMapImageFileName
        {
            get
            {
                return this.preUploadedMapImageFileNameField;
            }
            set
            {
                this.preUploadedMapImageFileNameField = value;
            }
        }
        
        /// <remarks/>
        public string PreUploadedBlankMapImageFileName
        {
            get
            {
                return this.preUploadedBlankMapImageFileNameField;
            }
            set
            {
                this.preUploadedBlankMapImageFileNameField = value;
            }
        }
        
        /// <remarks/>
        public string PreUploadedThumbnailImageFileName
        {
            get
            {
                return this.preUploadedThumbnailImageFileNameField;
            }
            set
            {
                this.preUploadedThumbnailImageFileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class PublishMapResponse
    {
        
        private bool successField;
        
        private string errorMessageField;
        
        private string uRLField;
        
        /// <remarks/>
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string URL
        {
            get
            {
                return this.uRLField;
            }
            set
            {
                this.uRLField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface DOMAServicePortTypeChannel : DomaMove.Doma.DOMAServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class DOMAServicePortTypeClient : System.ServiceModel.ClientBase<DomaMove.Doma.DOMAServicePortType>, DomaMove.Doma.DOMAServicePortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DOMAServicePortTypeClient() : 
                base(DOMAServicePortTypeClient.GetDefaultBinding(), DOMAServicePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DOMAServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DOMAServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(DOMAServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), DOMAServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DOMAServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DOMAServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DOMAServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DOMAServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DOMAServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<DomaMove.Doma.PublishMapResponse> PublishMapAsync(DomaMove.Doma.PublishMapRequest request)
        {
            return base.Channel.PublishMapAsync(request);
        }
        
        public System.Threading.Tasks.Task<DomaMove.Doma.PublishPreUploadedMapResponse> PublishPreUploadedMapAsync(DomaMove.Doma.PublishPreUploadedMapRequest request)
        {
            return base.Channel.PublishPreUploadedMapAsync(request);
        }
        
        public System.Threading.Tasks.Task<DomaMove.Doma.UploadPartialFileResponse> UploadPartialFileAsync(DomaMove.Doma.UploadPartialFileRequest request)
        {
            return base.Channel.UploadPartialFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<DomaMove.Doma.GetAllMapsResponse> GetAllMapsAsync(DomaMove.Doma.GetAllMapsRequest request)
        {
            return base.Channel.GetAllMapsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DomaMove.Doma.GetAllCategoriesResponse> GetAllCategoriesAsync(DomaMove.Doma.GetAllCategoriesRequest request)
        {
            return base.Channel.GetAllCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DomaMove.Doma.ConnectResponse> ConnectAsync(DomaMove.Doma.ConnectRequest request)
        {
            return base.Channel.ConnectAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DOMAServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DOMAServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://rystad.no/kart/webservice.php");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DOMAServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.DOMAServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DOMAServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.DOMAServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            DOMAServicePort,
        }
    }
}
